### ISSUE TITLE
Larger NIfTI images cause Jupyter Notebook to crash

### ISSUE THREAD

**Issue by kabilar** [niivue/ipyniivue#74] opened 2024-07-18 03:06 UTC
## Description

Hi Niivue team, thanks for your work on this package.

When using the code below for a ~10 MB NIfTI-GZ file, the image loads successfully.  For a larger NIfTI-GZ file (~200 MB), I receive the following error: `The extension host terminated unexpectedly. Restarting...`.  Is there a way to get around this issue?  Thank you.

```python
from ipyniivue import AnyNiivue, SliceType, DragMode

volumes = [
  { "path": "~/data.nii.gz", 
    "colormap": "gray", 
    "visible": True, 
    "opacity": 1.0, 
    "isHighResolutionCapable": False 
  },
]

nv = AnyNiivue(
    back_color=(0, 0, 0, 1),
    show_3D_crosshair=True,
    isCornerOrientationText=True,
    clip_plane_color=(1,0,0,1),
    is_colorbar=False,
    slice_type=SliceType.AXIAL,
    dragMode=DragMode.PAN
)

nv.load_volumes(volumes)
nv
```

## Reproducibility

I am running a Jupyter Notebook with a conda environment in VS Code on MacOS.  Below are a few of the relevant versions, but happy to provide a full list.
- ipyniivue 2.0.1
- anywidget 0.9.11
- notebook 7.2.0
- MacOS 14.5
- Apple M2 Pro

**Comment by kolibril13** [comment] 2024-07-18 17:52
hi @kabilar, thank you for your report! 

> For a larger NIfTI-GZ file (~200 MB), I receive the following error

Can you provide a link, so that we can download the file that is not loading correctly? 
Otherwise it will be difficult for us to reproduce your issue. 

Can you also try to drag and drop the file into this viewer instance from the original niivue project and see if it works?
https://niivue.github.io/niivue/features/draganddrop.html

We can then see if it's a niivue problem, or a problem in ipyniivue

**Comment by kolibril13** [comment] 2024-08-07 15:07
hi @kabilar, do you have further information for us?
Thanks!

**Comment by christian-oreilly** [comment] 2024-11-27 14:50
Closing this issue since we are missing information to reproduce the issue. If someone experiences the same problem and has an example of a large file that can be used to reproduce the problem, please reopen the ticket and share the file. We will then be happy to troubleshoot the issue.

**Comment by christian-oreilly** [comment] 2024-11-27 14:51
Closing this issue since we are missing information to reproduce the issue. If someone experiences the same problem and has an example of a large file that can be used to reproduce the problem, please reopen the ticket and share the file. We will then be happy to troubleshoot the issue.

**Closed by christian-oreilly** 2024-11-27 14:51 UTC

**Comment by kabilar** [comment] 2024-11-27 15:35
Thank you @kolibril13 @christian-oreilly.  I apologize for the lack of response here.  Our dataset it currently private so I unfortunately can't share it.  Will look for another dataset that has the same issue and that I can share publicly.
